---
title: "500-Cities_Project"
output: html_document
date: "'r Sys.Date()'"
---

### installing packages
```{r}
install.packages("renv") # handle dependency management
'renv::init()'
install.packages("dplyr") # manipulate dataframes
install.packages("readr") # read/write dataframes
install.packages("tidyr") # reshaping dataframes
install.packages("stringr") # string manipulation
install.packages("forcats") # factor manipulatlibrary(dplyr) # manipulate dataframes
install.packages("skimr")

### loading packages from library
library(readr) 
library(tidyr) 
library(stringr) 
library(forcats) 
library(purrr) 
library(ggplot2)
library(purrr) 
library(ggplot2)
```
# Import and Preview Dataset

This project uses the dataset '500 Cities Local Data for Better Health 2019 release from (https://chronicdata.cdc.gov/500-Cities-Places/500-Cities-Local-Data-for-Better-Health-2019-relea/6vp6-wxuq
https://chronicdata.cdc.gov/api/views/6vp6-wxuq/rows.csv?accessType=DOWNLOAD).

```{r}
library(fs) #cross-platform file system operations

df <- read_csv(path("500_Cities__Local_Data_for_Better_Health__2019_release.csv"))
```


